### ISSUE TITLE
support multiple benchmarks

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/cloud-weather-report#25]
We should be able to list multiple benchmarks per unit defined in the test plan, ie:

```
bundle: bundle:~bigdata-dev/bigtop-processing-mapreduce-6
benchmark:
    resourcemanager/0:
        mrbench
        nnbench
        terasort
bundle_name: bigtop-processing-mapreduce
bundle_file: bundle.yaml
```

I would expect the output to add a graph for each benchmark.

**Comment by seman** [comment]
Currently it doesn't support multiple benchmarks. This is beta release.

**Comment by kwmonroe** [comment]
Yup, understood.  Just logging it here as an issue / feature request.

FWIW, the code in `run_actions()` will already execute all benchmarks **if** they are enumerated as dicts, e.g.:

```
bundle: bundle:~bigdata-dev/bigtop-processing-mapreduce-6
benchmark:
    resourcemanager/0:
        mrbench:
            None
        nnbench:
            None
        terasort:
            None
bundle_name: bigtop-processing-mapreduce
bundle_file: bundle.yaml
```

So I think the only missing piece here would be generating graphs for each individual benchmark and writing those out to the results.html.
